service:
  title: HawkerFlow Service Hawker
  root_path: '/hawker'
  port: @port@
  host: '@host@'
  allow_origins:
    - '*'
  methods:
    - '*'
  headers:
    - '*'
  docs_url: '@docs_url@'
  redoc_url: '@redoc_url@'
  reload: true
  scheme: 'http'
  credentials: true

datasource:
  driver:
    package: "@package@"
    driver_class: "@drivername@"
  database:
    connection_url: 'sqlite:///database.db'
    driver_name: 'postgresql+psycopg2'
    name: 'hawkerflow_stall_db'
    host: '@db_host@'
    port: @db_port@
  options:
    echo: false